### PR TITLE
src, test: Refactoring of cover. 

### PR DESCRIPTION
**Pull request by Blebowski**
Rename "tag" to "item", and "tagging" to "ctx".

### CODE REVIEW

**Comment by nickg** [comment]
I don't like the name `cover_ctx_t` very much - can we rename it to `cover_data_t` instead?

**Comment by Blebowski** [comment]
Ok, not an issue. How would you then name local variables of `cover_data_t` type in `cover.c` ?
Something like: `data` (seems to generic and confusing). Maybe `cover_data` or simply `cover`
(as in rest of the code-base apart from `cover.c`) ? I would then unify it also in `model.c` , `nvc.c`
and other places.

**Comment by nickg** [comment]
Maybe `data` in `cover.c` and `cover` everywhere else.

**Comment by Blebowski** [comment]
Done

**Review by nickg — APPROVED** [review]

**Pull request merged**
